version: "3.9"
services:
  event-viewer:
    image: 'event_viewer'
    container_name: event-viewer
    command: Listen --subscribe-all
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - PRETTY=false
      - TOPIC_ARN=
